basedir=/afs/cern.ch/user/g/gdamolin/jobs_subm/Condor
executable=$(basedir)/RunDataset.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output                = $(basedir)/hello.$(ClusterId).$(ProcId).out
error                 = $(basedir)/hello.$(ClusterId).$(ProcId).err
log                   = $(basedir)/hello.$(ClusterId).log

+JobFlavour="workday"
queue arguments from $(basedir)/jobdescription.txt
