executable=/afs/cern.ch/user/g/gdamolin/jobs_subm/Condor/Python/RunDataset.py

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files=/afs/cern.ch/user/g/gdamolin/jobs_subm/Condor/Python/script.txt, /afs/cern.ch/user/g/gdamolin/private/x509up_u151129,



output                = /afs/cern.ch/user/g/gdamolin/Johan/output/hello.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/g/gdamolin/Johan/error/hello.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/g/gdamolin/Johan/log/hello.$(ClusterId).log

+JobFlavour="workday"
queue arguments from /afs/cern.ch/user/g/gdamolin/jobs_subm/Condor/Python/script.txt

